### ISSUE TITLE
Please commit the docker-compose.yml file

### ISSUE THREAD

**Issue by vonpupp** [johanan/Ansible-and-Docker#1]
Hello,

Your configs look very good, most of the configs I have found bloat the Dockerfile with several processes, which I disagree.

Could you please post your docker-compose file? If you could also post your variables example it would be great. It seems so that there are some missing vars like `VARNISH_PORT_80_TCP_ADDR` required for the frontnginx.

Thank you.

**Comment by johanan** [comment]
The docker-compose file is in the repo. It is under the ansible directory as it is parsed by ansible. You can find it at: https://github.com/johanan/Ansible-and-Docker/blob/master/ansible/roles/blog_site/templates/docker-compose.j2.

**Comment by vonpupp** [comment]
Thank you!

**Comment by johanan** [comment]
I also am open to any modifications. You mentioned some bloat in the Dockerfiles. Open a pull request and I will happy to check it out.

**Comment by vonpupp** [comment]
I was not referring to your config files when I said bloat, I was referring to what I have seen in general over the internet.
